# xhost +local:docker

services:
  o3de:
    image: husarion/o3de:1.1.0
    container_name: o3de_rosbot_xl
    runtime: nvidia
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host
    ipc: host
    environment:
      - DISPLAY=${DISPLAY:?err}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all

    command: bash -c "source /ros2_ws/install/setup.bash && ros2 launch rosbot_xl_o3de_slam slam.launch.py & /data/workspace/WarehouseTest/build/linux/bin/profile/Editor"