# Usage:
# xhost +local:docker && docker compose -f compose.sim.o3de.yaml up

x-net-config:
  &net-config
  network_mode: host
  ipc: host
  env_file: net.env

x-gpu-config:
  &gpu-config
  runtime: nvidia
  environment:
    - DISPLAY=${DISPLAY:?err}
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all

services:
  rviz:
    image: husarion/rviz2:galactic-8.5.2-20230204-stable
    <<: [ *net-config, *gpu-config ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_xl.rviz:/root/.rviz2/default.rviz
      - ./config/rosbot_xl.urdf:/robot_models/rosbot_xl.urdf

  rosbot-xl:
    image: husarion/o3de:1.2.0
    <<: [ *net-config, *gpu-config ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: /data/workspace/ROSbotXLDemo/build/linux/bin/profile/Editor
  
  mapping:
    image: husarion/slam-toolbox:humble-2.6.4-20230204-stable
    <<: *net-config
    volumes:
      - ./config/slam_toolbox_params.yaml:/slam_params.yaml
    command: >
      ros2 launch slam_toolbox online_sync_launch.py
        slam_params_file:=/slam_params.yaml
        use_sim_time:=True
  
  map-saver:
    image: husarion/nav2-map-server:humble-1.1.5-20230204-stable
    <<: *net-config
    volumes:
      - ./maps:/maps
    command: bash -c "while true; do ros2 run nav2_map_server map_saver_cli --free 0.15 --fmt png -f /maps/map; sleep 5; done"